name: Deploy Project
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install packags
        run: npm ci
      - name: lint
        run: npm run lint
  test_build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: test and build
        run: |
          npm test
          npm run build


