name: use issue event
on: issues

jobs:
  ouput:
    runs-on: ubuntu-latest
    steps:
      - name: output
        run: |
          echo "${{ toJSON(github.event_name) }}"
          echo "${{ toJSON(github.event) }}"